
#
# www.daytondv.com jekyll settings
#

# Site settings
title: Dayton Data Visualization
email: bowmanmc@gmail.com
description: Dayton Data Visualization Group
baseurl: ""
url: "http://www.daytondv.com"
twitter_username: daytondv
github_username:  daytondv

# Collections
collections:
    jobs:
        output: true
        permalink: /job/:path/
    sponsors:
        output: true
        permalink: /sponsor/:path/

# Build settings
markdown: kramdown
